name: Code linting
on:
  pull_request:
    types: opened
    branches:
      - develop
      - main
  workflow_dispatch:
  workflow_call:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint flask flask_wtf flask_sslify
      - name: Run Pylint
        run: |
          pylint --recursive=y --reports=y --rcfile=.pylintrc . | tee pylint_output.txt
          rating=$(grep -oE 'Your code has been rated at [0-9]+\.[0-9][0-9]+/10' pylint_output.txt | awk '{print $7}' | cut -d'/' -f1 | cut -d'.' -f1)
          if [[ "$rating" -lt 6 ]]; then echo "Low code rating, please fix them!" && exit 1; fi
