name: ci pipeline
on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
      - develop
  workflow_dispatch:
  push:
    branches: develop
  workflow_call:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks scan
        run: |
          git clone https://github.com/gitleaks/gitleaks.git
          cd gitleaks
          make build
          gitleaks detect --no-git --verbose --redact . 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
